/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWebhooksRouteImport } from './routes/_app.webhooks'
import { Route as AppSpiffRouteImport } from './routes/_app.spiff'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppQuotesRouteImport } from './routes/_app.quotes'
import { Route as AppPricingRouteImport } from './routes/_app.pricing'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppLogisticsRouteImport } from './routes/_app.logistics'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppDamageRouteImport } from './routes/_app.damage'
import { Route as AppCatalogsRouteImport } from './routes/_app.catalogs'
import { Route as AppBridgeRouteImport } from './routes/_app.bridge'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppArRouteImport } from './routes/_app.ar'
import { Route as ApiPublicP21BridgeRouteImport } from './routes/api/public/p21-bridge'
import { Route as ApiPublicInboundEmailRouteImport } from './routes/api/public/inbound-email'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppSpiffRoute = AppSpiffRouteImport.update({
  id: '/spiff',
  path: '/spiff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesRoute = AppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppDamageRoute = AppDamageRouteImport.update({
  id: '/damage',
  path: '/damage',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogsRoute = AppCatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => AppRoute,
} as any)
const AppBridgeRoute = AppBridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppArRoute = AppArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicP21BridgeRoute = ApiPublicP21BridgeRouteImport.update({
  id: '/api/public/p21-bridge',
  path: '/api/public/p21-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboundEmailRoute = ApiPublicInboundEmailRouteImport.update({
  id: '/api/public/inbound-email',
  path: '/api/public/inbound-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/ar': typeof AppArRoute
  '/audit': typeof AppAuditRoute
  '/bridge': typeof AppBridgeRoute
  '/catalogs': typeof AppCatalogsRoute
  '/damage': typeof AppDamageRoute
  '/inbox': typeof AppInboxRoute
  '/inventory': typeof AppInventoryRoute
  '/logistics': typeof AppLogisticsRoute
  '/orders': typeof AppOrdersRoute
  '/pricing': typeof AppPricingRoute
  '/quotes': typeof AppQuotesRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/spiff': typeof AppSpiffRoute
  '/webhooks': typeof AppWebhooksRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/p21-bridge': typeof ApiPublicP21BridgeRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ar': typeof AppArRoute
  '/audit': typeof AppAuditRoute
  '/bridge': typeof AppBridgeRoute
  '/catalogs': typeof AppCatalogsRoute
  '/damage': typeof AppDamageRoute
  '/inbox': typeof AppInboxRoute
  '/inventory': typeof AppInventoryRoute
  '/logistics': typeof AppLogisticsRoute
  '/orders': typeof AppOrdersRoute
  '/pricing': typeof AppPricingRoute
  '/quotes': typeof AppQuotesRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/spiff': typeof AppSpiffRoute
  '/webhooks': typeof AppWebhooksRoute
  '/': typeof AppIndexRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/p21-bridge': typeof ApiPublicP21BridgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/ar': typeof AppArRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/bridge': typeof AppBridgeRoute
  '/_app/catalogs': typeof AppCatalogsRoute
  '/_app/damage': typeof AppDamageRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/logistics': typeof AppLogisticsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/quotes': typeof AppQuotesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/spiff': typeof AppSpiffRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/p21-bridge': typeof ApiPublicP21BridgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ar'
    | '/audit'
    | '/bridge'
    | '/catalogs'
    | '/damage'
    | '/inbox'
    | '/inventory'
    | '/logistics'
    | '/orders'
    | '/pricing'
    | '/quotes'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/spiff'
    | '/webhooks'
    | '/api/public/inbound-email'
    | '/api/public/p21-bridge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ar'
    | '/audit'
    | '/bridge'
    | '/catalogs'
    | '/damage'
    | '/inbox'
    | '/inventory'
    | '/logistics'
    | '/orders'
    | '/pricing'
    | '/quotes'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/spiff'
    | '/webhooks'
    | '/'
    | '/api/public/inbound-email'
    | '/api/public/p21-bridge'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/ar'
    | '/_app/audit'
    | '/_app/bridge'
    | '/_app/catalogs'
    | '/_app/damage'
    | '/_app/inbox'
    | '/_app/inventory'
    | '/_app/logistics'
    | '/_app/orders'
    | '/_app/pricing'
    | '/_app/quotes'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/spiff'
    | '/_app/webhooks'
    | '/_app/'
    | '/api/public/inbound-email'
    | '/api/public/p21-bridge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicInboundEmailRoute: typeof ApiPublicInboundEmailRoute
  ApiPublicP21BridgeRoute: typeof ApiPublicP21BridgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spiff': {
      id: '/_app/spiff'
      path: '/spiff'
      fullPath: '/spiff'
      preLoaderRoute: typeof AppSpiffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes': {
      id: '/_app/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AppQuotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logistics': {
      id: '/_app/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/damage': {
      id: '/_app/damage'
      path: '/damage'
      fullPath: '/damage'
      preLoaderRoute: typeof AppDamageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogs': {
      id: '/_app/catalogs'
      path: '/catalogs'
      fullPath: '/catalogs'
      preLoaderRoute: typeof AppCatalogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bridge': {
      id: '/_app/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof AppBridgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ar': {
      id: '/_app/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof AppArRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/p21-bridge': {
      id: '/api/public/p21-bridge'
      path: '/api/public/p21-bridge'
      fullPath: '/api/public/p21-bridge'
      preLoaderRoute: typeof ApiPublicP21BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound-email': {
      id: '/api/public/inbound-email'
      path: '/api/public/inbound-email'
      fullPath: '/api/public/inbound-email'
      preLoaderRoute: typeof ApiPublicInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppArRoute: typeof AppArRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBridgeRoute: typeof AppBridgeRoute
  AppCatalogsRoute: typeof AppCatalogsRoute
  AppDamageRoute: typeof AppDamageRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPricingRoute: typeof AppPricingRoute
  AppQuotesRoute: typeof AppQuotesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpiffRoute: typeof AppSpiffRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArRoute: AppArRoute,
  AppAuditRoute: AppAuditRoute,
  AppBridgeRoute: AppBridgeRoute,
  AppCatalogsRoute: AppCatalogsRoute,
  AppDamageRoute: AppDamageRoute,
  AppInboxRoute: AppInboxRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPricingRoute: AppPricingRoute,
  AppQuotesRoute: AppQuotesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpiffRoute: AppSpiffRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicInboundEmailRoute: ApiPublicInboundEmailRoute,
  ApiPublicP21BridgeRoute: ApiPublicP21BridgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
