// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const unauthorized = (message: string): never => {
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    };
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      unauthorized('Unauthorized: No request headers available');
    }

    const authHeaderValue = request.headers.get('authorization');

    if (!authHeaderValue) {
      unauthorized('Unauthorized: No authorization header provided');
    }

    const authHeader = authHeaderValue;

    if (!authHeader.startsWith('Bearer ')) {
      unauthorized('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      unauthorized('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data: claimsData, error } = await supabase.auth.getClaims(token);
    if (error || !claimsData?.claims) {
      unauthorized('Unauthorized: Invalid token');
    }

    const claims = claimsData.claims;

    if (!claims.sub) {
      unauthorized('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: claims.sub,
        claims,
      },
    })
  }
)
